<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>1315e618-bdbb-4ef7-9974-5761ed98b9d4</UserSecretsId>
    <NoWarn>ASPIREBROWSERLOGS001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Garage.ApiService\Garage.ApiService.csproj" />
    <ProjectReference Include="..\Garage.ServiceDefaults\Garage.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Azure.Redis" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.Browsers" />
    <PackageReference Include="Aspire.Hosting.DevTunnels" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.Foundry" />
    <PackageReference Include="Aspire.Hosting.Go" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Python" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Flagd" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.k6" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.OpenTelemetryCollector" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

</Project>
